apiVersion: v2
name: kyverno-policies
version: 1.1.0-bb.6
appVersion: 1.1.0
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
description: Collection of Kyverno security and best-practice policies for Kyverno
keywords:
  - kyverno
  - nirmata
  - policy agent
  - policies
home: https://kyverno.io/policies/
sources:
  - https://github.com/kyverno/policies
dependencies:
  - name: gluon
    version: 0.3.1
    repository: oci://registry1.dso.mil/bigbang
annotations:
  bigbang.dev/applicationVersions: |
    - Kyverno Policies: 1.1.0
  # Kubectl image is used if waitforready.enabled or bbtests.enabled
  helm.sh/images: |
    - name: kubectl
      image: registry1.dso.mil/ironbank/opensource/kubernetes/kubectl:v1.26.4
