{{- $name := "cve-2021-44228" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: CVE-2021-44228 - Log4j2 Mitigation
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/severity: {{ default "critical" (dig $name "severity" nil .Values.policies) }}
    policies.kyverno.io/category: Vulnerability
    policies.kyverno.io/description: >-
      Apache Log4j2 2.0-beta9 through 2.12.1 and 2.13.0 through 2.15.0 JNDI features used in
      configuration, log messages, and parameters do not protect against attacker controlled
      LDAP and other JNDI related endpoints. For Log4j versions >= 2.10, the environment variable
      LOG4J_FORMAT_MSG_NO_LOOKUPS can be set to true to mitigate this vulnerability. This policy
      will mutate all initContainers and containers in an incoming Pod to add this setting.
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "kyverno-policies.webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  rules:
  - name: add-log4shell-mitigation-initcontainers
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "Pod")) .) | nindent 4 }}
    mutate:
      patchStrategicMerge:
        spec:
          initContainers:
            - (name): "*"
              env:
              - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
                value: "true"
  - name: add-log4shell-mitigation-containers
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "Pod")) .) | nindent 4 }}
    mutate:
      patchStrategicMerge:
        spec:
          containers:
            - (image): "*"
              env:
              - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
                value: "true"
{{- end -}}