{{- $name := "disallow-subpath-volumes" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Disallow SubPath Volumes (CVE-2021-25741)
    policies.kyverno.io/category: Vulnerability
    policies.kyverno.io/severity: {{ default "high" (dig $name "severity" nil .Values.policies) }}
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      A security issue was discovered in Kubernetes where a user may be able to create a container with
      subpath volume mounts to access files and directories outside of the volume, including on the host
      filesystem.  This policy denies containers that use volume mounts with subpaths.  See the CVE
      for applicable Kubernetes versions.
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "kyverno-policies.webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  validationFailureAction: {{ default (dig $name "validationFailureAction" nil .Values.policies) .Values.validationFailureAction }}
  rules:
  - name: subpath-volume-mounts
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "Pod")) .) | nindent 4 }}
    validate:
      message: >-
        Volume mounts with a subPath are forbidden. The fields spec.containers[*].subPath, spec.initContainers[*].subPath,
        spec.ephemeralContainers[*].subPath, spec.containers[*].subPathExpr, spec.initContainers[*].subPathExpr, and
        spec.ephemeralContainers[*].subPathExpr must not be set.
      pattern:
        spec:
          =(initContainers):
            - =(volumeMounts):
              - X(subPath): "null"
                X(subPathExpr): "null"
          containers:
            - =(volumeMounts):
              - X(subPath): "null"
                X(subPathExpr): "null"
          # Volume mounts with subpaths are not allowed for ephemeral containers, but included here in case it changes
          =(ephemeralContainers):
            - =(volumeMounts):
              - X(subPath): "null"
                X(subPathExpr): "null"
{{- end -}}