{{- $name := "disallow-selinux-options" }}
{{- $failureAction := default (dig $name "validationFailureAction" nil .Values.policies) .Values.validationFailureAction }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    {{- include "kyverno-policies.annotations" . | nindent 4 }}
    {{- with .Values.autogenControllers }}
    pod-policies.kyverno.io/autogen-controllers: {{ . }}
    {{- end }}
    policies.kyverno.io/title: Disallow SELinux Options
    policies.kyverno.io/category: Pod Security Standards (Baseline)
    policies.kyverno.io/severity: {{ default "high" (dig $name "severity" nil .Values.policies) }}
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      SELinux options can be used to escalate privileges. This policy ensures that the `seLinuxOptions`
      specified are not used.
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "kyverno-policies.webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  validationFailureAction: {{ $failureAction }}
  background: {{ .Values.background }}
  failurePolicy: {{ default .Values.failurePolicy (include "setFailurePolicy" $failureAction) }}
  rules:
  {{- range $v := (dig $name "parameters" "disallow" nil .Values.policies) }}
  - name: pod-disallow-selinux-{{ $v }}
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) $) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "Pod")) $) | nindent 4 }}
    {{- with index $.Values "policyPreconditions" $name }}
    preconditions:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    validate:
      message: >-
        Setting SELinux {{ $v }} is not allowed.  The fields spec.securityContext.seLinuxOptions.{{ $v }},
        spec.containers[*].securityContext.seLinuxOptions.{{ $v }}, spec.initContainers[*].securityContext.seLinuxOptions.{{ $v }},
        and spec.ephemeralContainers[*].securityContext.seLinuxOptions.{{ $v }} must be undefined.
      pattern:
        spec:
          =(securityContext):
            =(seLinuxOptions):
              X({{ $v }}): "null"
  - name: container-disallow-selinux-{{ $v }}
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) $) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "Pod")) $) | nindent 4 }}
    {{- with index $.Values "policyPreconditions" $name }}
    preconditions:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    validate:
      message: >-
        Setting SELinux {{ $v }} is not allowed.  The fields spec.securityContext.seLinuxOptions.{{ $v }},
        spec.containers[*].securityContext.seLinuxOptions.{{ $v }}, spec.initContainers[*].securityContext.seLinuxOptions.{{ $v }},
        and spec.ephemeralContainers[*].securityContext.seLinuxOptions.{{ $v }} must be undefined.
      {{- include "kyverno-policies.excludeContainers" (merge (dict "name" $name) $) | nindent 6 }}
            pattern:
              =(securityContext):
                =(seLinuxOptions):
                  X({{ $v }}): "null"
  {{- end }}
{{- end -}}
