{{- $name := "disallow-auto-mount-service-account-token" }}
{{- $failureAction := default (dig $name "validationFailureAction" nil .Values.policies) .Values.validationFailureAction  }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    {{- include "kyverno-policies.annotations" . | nindent 4 }}
    policies.kyverno.io/title: Disallow AutoMount Service Account Tokens
    policies.kyverno.io/category: Pod Security Standards (Baseline)
    policies.kyverno.io/severity: {{ default "high" (dig $name "severity" nil .Values.policies) }}
    policies.kyverno.io/subject: Pod, ServiceAccount
    policies.kyverno.io/description: >-
      Automouting of Kubernetes API credentials is not ideal in all circumstances. This policy finds Pods and Service Accounts
      that automount kubernetes api credentials.
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "kyverno-policies.webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  validationFailureAction: {{ $failureAction }}
  failurePolicy: {{ default .Values.failurePolicy (include "setFailurePolicy" $failureAction) }}
  rules:
  - name: automount-pods
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "Pod" "StatefulSet" "Deployment")) .) | nindent 4 }}
    {{- with index .Values "policyPreconditions" $name }}
    preconditions:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    validate:
      message: >-
        Automount Kubernetes API Credentials is explicitly turned on. The field spec.automountServiceAccountToken 
        must be undefined or set to false.
      pattern:
        spec:
          =(automountServiceAccountToken): false
          =(template):
            =(spec):
              =(automountServiceAccountToken): false
  - name: automount-service-accounts
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "ServiceAccount")) .) | nindent 4 }}
    {{- with index .Values "policyPreconditions" $name }}
    preconditions:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    validate:
      message: >-
        Automount Kubernetes API Credentials isn't turned off. The field automountServiceAccountToken 
        must be set to false.
      pattern:
        automountServiceAccountToken: false
{{- end -}}
