{{- $name := "require-non-root-group" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) .Values.istio.enabled }}
apiVersion:  kyverno.io/v2
kind: PolicyException
metadata:
  name: {{ $name }}-exception
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "kyverno-policies.annotations" . | nindent 4 }}
spec:
  exceptions:
  - policyName: {{ $name }}
    ruleNames:
    - run-as-group
  match:
    any:
    - resources:
        kinds:
        - Pods/containers
        names:
        - istio-init
{{- end }}
