{{- $name := "require-non-root-user" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) .Values.istio.enabled }}
apiVersion:  kyverno.io/v2
kind: PolicyException
metadata:
  name: {{ $name }}-exception
  namespace: {{ .Release.Namespace }}
spec:
  exceptions:
  - policyName: {{ $name }}
    ruleNames:
    - non-root-user
  match:
    any:
    - resources:
        kinds:
        - Pods/containers
        names:
        - istio-init
{{- end }}
