{{- $name := "require-resource-limits" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Require Resource Limits
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: {{ default "medium" (dig $name "severity" nil .Values.policies) }}
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      As application workloads share cluster resources, it is important to limit cpu and memory resources
      in containers to prevent resource exhaustion and denial-of-service.  Each container should have a
      cpu and memory limit defined.  Kubernetes will automatically assign resource requests to limits if
      they are left undefined. If a Namespace level request or limit is specified, defaults will automatically
      be applied to each Pod based on the LimitRange configuration.  This policy validates that all containers
      have memory and CPU limits defined.
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "kyverno-policies.webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  validationFailureAction: {{ default (dig $name "validationFailureAction" nil .Values.policies) .Values.validationFailureAction }}
  rules:
  - name: validate-resources
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "Pod")) .) | nindent 4 }}
    validate:
      message: "CPU and memory resource limits are required on all containers."
      pattern:
        spec:
          containers:
          - resources:
              limits:
                memory: "?*"
                cpu: "?*"
          =(initContainers):
          - resources:
              limits:
                memory: "?*"
                cpu: "?*"
          =(ephemeralContainers):
          - resources:
              limits:
                memory: "?*"
                cpu: "?*"
{{- end -}}
