{{- $name := "restrict-capabilities" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Restrict Capabilities
    policies.kyverno.io/category: Pod Security Standards (Baseline)
    policies.kyverno.io/severity: {{ default "medium" (dig $name "severity" nil .Values.policies) }}
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Capabilities permit privileged actions without giving full root access.
      Adding capabilities beyond the default set must not be allowed. This policy
      ensures users cannot add additional capabilities beyond the allowed list to a Pod.
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "kyverno-policies.webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  validationFailureAction: {{ default (dig $name "validationFailureAction" nil .Values.policies) .Values.validationFailureAction }}
  background: true
  rules:
    - name: capabilities
      {{- include "kyverno-policies.context" (merge (dict "name" $name) .) | indent 6 }}
      {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 6 }}
      {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "Pod")) .) | nindent 6 }}
      validate:
        message: >-
          Adding of additional capabilities beyond the allowed set is not allowed.
          The fields spec.containers[*].securityContext.capabilities.add and
          spec.initContainers[*].securityContext.capabilities.add must be in the allowedCapabilities list.
        pattern:
          spec:
            containers:
              - =(securityContext):
                  =(capabilities):
                    =(add): "{{ "{{" }}configmap.data.allowedCapabilities{{ "}}" }}"
            =(initContainers):
              - =(securityContext):
                  =(capabilities):
                    =(add): "{{ "{{" }}configmap.data.allowedCapabilities{{ "}}" }}"

---
{{ include "kyverno-policies.configmap" (merge (dict "name" $name) .) }}
{{- end -}}
