{{- $name := "update-automountserviceaccounttokens-default" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Disable automountServiceAccountToken
    policies.kyverno.io/category: Other, EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: ServiceAccount
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.21"
    policies.kyverno.io/description: >-
      A new ServiceAccount called `default` is created whenever a new Namespace is created.
      Pods spawned in that Namespace, unless otherwise set, will be assigned this ServiceAccount.
      This policy mutates any new `default` ServiceAccounts to disable auto-mounting of the token
      into Pods obviating the need to do so individually.      
spec:
  background: {{ .Values.background }}
  failurePolicy: {{ .Values.failurePolicy }}
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: mutate-default-serviceaccount-tokens
    match:
      any:
      - resources:
          kinds:
          - ServiceAccount
          names:
          - default 
    mutate:
      patchStrategicMerge:
        automountServiceAccountToken: false
      targets:
      {{- range $v := (dig $name "namespaces" nil .Values.policies) }}
      - apiVersion: v1
        kind: ServiceAccount
        name: default
        namespace: {{ . }}
      {{- end -}}
{{- end -}}
